create a NumPy array called nums containing the values 1, 3, 5, 7, 9, print the array, add 2 to each element and store the result in a new array, multiply each element by 3, and then use NumPy methods to find and print the sum, maximum value, and mean of the original array.

In [1]:
import numpy as np

In [2]:
nums = np.array([ 1, 3, 5, 7, 9])
print(nums)

[1 3 5 7 9]


In [3]:
new_array = nums + 2
print(new_array)

[ 3  5  7  9 11]


In [4]:
array_3 = nums * 3
print(array_3)

[ 3  9 15 21 27]


In [6]:
total_array = np.sum(nums)
print(total_array)
max_array = np.max(nums)
print(max_array)
mean_array = np.mean(nums)
print(mean_array)

25
9
5.0
