#create a NumPy array called nums containing the values 1, 3, 5, 7, 9, print the array, add 2 to each element and store the result in a new array, multiply each element by 3, and then use NumPy methods to find and print the sum, maximum value, and mean of the original array.#

In [1]:
import numpy as np

In [2]:
nums = np. array ([1,3,5,7,9])
print(nums)

[1 3 5 7 9]


In [3]:
new_array = nums + 2
print(new_array)

[ 3  5  7  9 11]


In [4]:
present_array  = new_array * 3
print(present_array)

[ 9 15 21 27 33]


In [7]:
total_sum = np.sum(nums)
print(f"sum:{total_sum}")
maximum_value = np.max(nums)
print(f"maximum_value:{maximum_value}")
mean = np.mean(nums)
print(F"mean:{mean}")

sum:25
maximum_value:9
mean:5.0
