In [7]:
import numpy as np
num_1 = np.array([1,3,5,7,9])


In [8]:
print(num_1)

[1 3 5 7 9]


In [9]:
num_1 =np.array(num_1 + 2)

In [10]:
print(num_1)

[ 3  5  7  9 11]


In [14]:
num_1 = np.array(num_1 * 3)

In [16]:
print(num_1)

[ 9 15 21 27 33]


In [21]:
total = np.sum(num_1)
Maximum = np.max(num_1)
Average = np.mean(num_1)
print('sum:', total)
print('Maximum Value:', Maximum)
print('mean:', Average)

sum: 105
Maximum Value: 33
mean: 21.0
